"""Observer-relative public knowledge; never return hidden detail to the client."""
from .incident_definitions import BY_ID
from .definitions import default_site
from .state import get_echo


WORLD_TIERS = dict(human=1, demon=1, monster_realm=2, hell=2,
                   spirit=2, true_demon=2, phantom_underworld=2,
                   celestial=3, asura=3, nether=3, reincarnation=3)
WORLD_NAMES = dict(human='人界', demon='魔界', monster_realm='妖界', hell='地狱界',
                   spirit='灵界', true_demon='真魔界', phantom_underworld='幻冥界',
                   celestial='仙界', asura='修罗界', nether='幽冥界', reincarnation='轮回界')


def level(observer, subject):
    """Direct knowledge of peers/lower worlds; rumours one tier up, signs above."""
    gap = WORLD_TIERS.get(subject, 3) - WORLD_TIERS.get(observer, 1)
    return 5 if gap <= 0 else 2 if gap == 1 else 1


def knows(game, identity):
    desc = BY_ID.get(identity) or default_site(identity)
    runtime = game.heavens_state.get('runtime', {})
    return (not desc or level(game.player.world, desc.world) == 5
            or identity in runtime.get('incidents', {}) or bool(get_echo(runtime, identity)))


def news(game, *, subject=None, purchased_level=None):
    result = []
    # Existing wars alone are evidence of war; static content is not a battle.
    for war in game.wars[-12:]:
        world = war.get('world')
        if world not in WORLD_TIERS or subject is not None and world != subject:
            continue
        visibility = purchased_level or level(game.player.world, world)
        if visibility == 1:
            row = dict(level=1, title='灵气异动', text='最近小周天内灵气波动有些异常，缘由尚不可知。')
        elif visibility == 2:
            row = dict(level=2, title='远界传闻', text=f'听说{WORLD_NAMES[world]}曾有势力交战，具体地点与胜负尚无确讯。')
        elif visibility == 3:
            names = []
            for side in ('attacker', 'defender'):
                entity = game.sects.get(war.get(side + '_id'))
                names.append(entity.name if entity else '身份尚未核实的势力')
            status = '仍在交战' if war.get('status') == 'active' else '已结束交战'
            row = dict(level=3, title=f'{WORLD_NAMES[world]}战事简报',
                       text=f'{names[0]}与{names[1]}{status}，地点与具体战果尚待核实。', world=world)
        else:
            logs = war.get('logs', [])
            # Logs were generated by the real war system, including real actors,
            # locations and outcomes. Do not synthesize results for unfinished wars.
            row = dict(level=visibility, title=f'{WORLD_NAMES[world]}战事' + ('详报' if visibility == 4 else '全卷'),
                       text='\n'.join(str(entry.get('text', '')) for entry in logs[-(3 if visibility == 4 else 12):]) or '已有交战记录，尚未收到战果。',
                       world=world, status=war.get('status'), war_id=war['id'])
            if visibility == 5:
                details = []
                if 'battles' in war:
                    details.append(f"已记录交战 {war['battles']} 次")
                for side, label in (('attacker', '进攻方'), ('defender', '防守方')):
                    if side in war.get('morale', {}):
                        details.append(f"{label}士气 {war['morale'][side]:g}")
                    if side in war.get('exhaustion', {}):
                        details.append(f"{label}疲敝 {war['exhaustion'][side]:g}")
                if details:
                    row['text'] += '\n' + '；'.join(details) + '。'
        if row not in result:
            result.append(row)
    return result


def acquire_merchant_reports(game, world, stars):
    """Called only by a completed real merchant intelligence commission."""
    reports = news(game, subject=world, purchased_level=max(1, min(5, int(stars))))
    ledger = game.merchant_state.setdefault('heavens_reports', [])
    for row in reports:
        row.update(source='跨界商盟情报委托', acquired_age=game.player.age)
        if row not in ledger:
            ledger.append(row)
    game.merchant_state['heavens_reports'] = ledger[-32:]
    return '；'.join(row['text'] for row in reports) or '未核实到该界近期战事'


def restrict(game, result):
    for key in ('incidents', 'anomalies', 'conflicts'):
        result[key] = [row for row in result.get(key, []) if knows(game, row['id'])]
    # Contact dossiers belong to the highest layer. Lower worlds may receive
    # actual rumours, but may not enumerate their locations, actors or actions.
    result['sites'] = [row for row in result['sites'] if row['known'] or level(game.player.world, row['world']) == 5]
    visible_sites = {row['id'] for row in result['sites']}
    result['upkeeps'] = [row for row in result.get('upkeeps', []) if row.get('target_id') in visible_sites]
    result['intelligence'] = news(game) + game.merchant_state.get('heavens_reports', [])[-32:]
    for key in ('migrations', 'upkeeps'):
        result[key] = [row for row in result.get(key, []) if row.get('target_id') in visible_sites]
    result['records'] = [row for row in result.get('records', []) if row.get('id') not in {'sea_echo', 'asura_echo', 'nether_echo', 'reincarnation_echo'} or row['id'] in visible_sites]
    if not result['sites']:
        result['reason'] = '远界的具体地点尚不可知，消息以当前能够辨识的层级呈现。'
    return result
