"""Second-generation simulation runtime.

The V2 package is deliberately isolated from the legacy ``GameEngine``.  It
does not import legacy models or save stores, which lets the new runtime be
built and verified without changing existing saves.
"""

from .application import LegacyImportExecution, V2GameEngine
from .domain.character import PerformTimedAction, RegisterCharacter
from .domain.cultivation import (
    AttemptBreakthrough,
    EquipMainTechnique,
    GrantTechnique,
    PerformActionUnits,
)
from .domain.advanced_cultivation import (
    AbsorbTransformationMaterial,
    AttemptBodyBreakthrough,
    AttemptDivineSenseBreakthrough,
    EquipSpecialTechnique,
    ManageTransformation,
)
from .domain.factions import (
    ChangeContribution,
    FoundFaction,
    JoinFaction,
    InviteRelationshipToFaction,
    SetFactionRewardPreference,
    LeaveFaction,
    TransferFactionControl,
)
from .domain.combat import ResolveCombat, RestoreCombatCondition
from .domain.economy import (
    BuyMarketOffer,
    GrantItem,
    RefreshMarket,
    ToggleMarketOfferLock,
    UseItem,
)
from .domain.production import (
    HarvestSpiritCrop,
    IrrigateSpiritCrop,
    PlantSpiritCrop,
    ReclaimSpiritField,
    RefinePill,
    SellSpiritPlant,
    UseHarvestedPlant,
)
from .domain.auction import (
    AdvanceAuctionRound,
    BargainPrivateTrade,
    BuyBlackMarket,
    BuyPrivateTrade,
    ChooseAuctionIdentity,
    ConsignAuctionAsset,
    LeaveBlackMarket,
    NegotiateAuction,
    PlaceAuctionBid,
    ScheduleAuction,
    SearchBlackMarket,
    SellBlackMarketAsset,
    SellPrivateTrade,
)
from .domain.artifacts import (
    ActivateFormation,
    DeactivateFormation,
    DeleteFormation,
    DeployGroundFormation,
    ForgeArtifact,
    ManageNatalArtifact,
    PreviewCrafting,
    PreviewFormation,
    RepairGroundFormation,
    SaveCraftingBlueprint,
    SaveFormation,
    SellCraftedArtifact,
    WithdrawGroundFormation,
)
from .domain.extensions import (
    AssignFactionPosition,
    ConfigureMonsterBloodline,
    SpendWangsheng,
)
from .domain.relations import (
    BefriendDaoist,
    ChangeAffinity,
    EndRelationship,
    FormRelationship,
    GiftDisciple,
    InteractDaoCompanion,
    InteractDaoFriend,
    OfferDiscipleRequest,
    ProposeDaoCompanion,
    RequestFromMaster,
    RequestMentorship,
    RespondDiscipleRequest,
)
from .domain.world import AscendWorld, CrossWorld, TravelWithinWorld
from .domain.story import QueueStoryEvent, ResolveStoryChoice
from .domain.trials import BeginAscensionTrial

__all__ = [
    "AttemptBreakthrough",
    "AttemptBodyBreakthrough",
    "AttemptDivineSenseBreakthrough",
    "AscendWorld",
    "AbsorbTransformationMaterial",
    "AssignFactionPosition",
    "BuyMarketOffer",
    "BeginAscensionTrial",
    "ChangeContribution",
    "ConfigureMonsterBloodline",
    "CrossWorld",
    "ChangeAffinity",
    "EndRelationship",
    "EquipMainTechnique",
    "EquipSpecialTechnique",
    "FormRelationship",
    "BefriendDaoist",
    "GiftDisciple",
    "InteractDaoCompanion",
    "InteractDaoFriend",
    "OfferDiscipleRequest",
    "ProposeDaoCompanion",
    "RequestFromMaster",
    "RequestMentorship",
    "RespondDiscipleRequest",
    "FoundFaction",
    "GrantItem",
    "GrantTechnique",
    "HarvestSpiritCrop",
    "IrrigateSpiritCrop",
    "JoinFaction",
    "ManageTransformation",
    "InviteRelationshipToFaction",
    "SetFactionRewardPreference",
    "LeaveFaction",
    "PerformActionUnits",
    "PerformTimedAction",
    "PlantSpiritCrop",
    "RefreshMarket",
    "ReclaimSpiritField",
    "RefinePill",
    "ResolveStoryChoice",
    "QueueStoryEvent",
    "RegisterCharacter",
    "ResolveCombat",
    "RestoreCombatCondition",
    "SpendWangsheng",
    "SellSpiritPlant",
    "ToggleMarketOfferLock",
    "TransferFactionControl",
    "TravelWithinWorld",
    "UseHarvestedPlant",
    "UseItem",
    "V2GameEngine",
    "LegacyImportExecution",
    "AdvanceAuctionRound",
    "BargainPrivateTrade",
    "BuyBlackMarket",
    "BuyPrivateTrade",
    "ChooseAuctionIdentity",
    "ConsignAuctionAsset",
    "LeaveBlackMarket",
    "NegotiateAuction",
    "PlaceAuctionBid",
    "ScheduleAuction",
    "SearchBlackMarket",
    "SellBlackMarketAsset",
    "SellPrivateTrade",
    "ActivateFormation",
    "DeactivateFormation",
    "DeleteFormation",
    "DeployGroundFormation",
    "ForgeArtifact",
    "ManageNatalArtifact",
    "PreviewCrafting",
    "PreviewFormation",
    "RepairGroundFormation",
    "SaveCraftingBlueprint",
    "SaveFormation",
    "SellCraftedArtifact",
    "WithdrawGroundFormation",
]
