"""Named dependency builders for world."""
from __future__ import annotations

from typing import TYPE_CHECKING, Callable

from ..dependencies import (
    NpcDependencies,
    RelationshipDependencies,
    FactionDependencies,
    HostilityDependencies,
)

if TYPE_CHECKING:
    from .. import GameEngine


def bind_npcs(engine: GameEngine) -> NpcDependencies:
    return NpcDependencies(
        _advance_merchant_year=lambda *args, **kwargs: engine._advance_merchant_year(*args, **kwargs),
        _advance_npc_cultivation=lambda *args, **kwargs: engine._advance_npc_cultivation(*args, **kwargs),
        _all_world_npcs=lambda *args, **kwargs: engine._all_world_npcs(*args, **kwargs),
        _ascension_destination=lambda *args, **kwargs: engine._ascension_destination(*args, **kwargs),
        _cultivation_sense_requirement=lambda *args, **kwargs: engine._cultivation_sense_requirement(*args, **kwargs),
        _ensure_npc_concealment=lambda *args, **kwargs: engine._ensure_npc_concealment(*args, **kwargs),
        _ensure_sect_relations=lambda *args, **kwargs: engine._ensure_sect_relations(*args, **kwargs),
        _find_npc=lambda *args, **kwargs: engine._find_npc(*args, **kwargs),
        _instantiate_event=lambda *args, **kwargs: engine._instantiate_event(*args, **kwargs),
        _intrigue_is_imprisoned=lambda *args, **kwargs: engine._intrigue_is_imprisoned(*args, **kwargs),
        _maybe_notorious_npc_killing=lambda *args, **kwargs: engine._maybe_notorious_npc_killing(*args, **kwargs),
        _mortal_root_completion_chance=lambda *args, **kwargs: engine._mortal_root_completion_chance(*args, **kwargs),
        _npc_breakthrough_probability=lambda *args, **kwargs: engine._npc_breakthrough_probability(*args, **kwargs),
        _npc_faction_id=lambda *args, **kwargs: engine._npc_faction_id(*args, **kwargs),
        _npc_lifespan_multiplier=lambda *args, **kwargs: engine._npc_lifespan_multiplier(*args, **kwargs),
        _npc_power=lambda *args, **kwargs: engine._npc_power(*args, **kwargs),
        _npc_realm_name=lambda *args, **kwargs: engine._npc_realm_name(*args, **kwargs),
        _npc_root_efficiency=lambda *args, **kwargs: engine._npc_root_efficiency(*args, **kwargs),
        _random_npc_path=lambda *args, **kwargs: engine._random_npc_path(*args, **kwargs),
        _random_npc_root=lambda *args, **kwargs: engine._random_npc_root(*args, **kwargs),
        _recruit_realm_index=lambda *args, **kwargs: engine._recruit_realm_index(*args, **kwargs),
        _recruit_sect_npc=lambda *args, **kwargs: engine._recruit_sect_npc(*args, **kwargs),
        _resolve_npc_periodic_tribulation=lambda *args, **kwargs: engine._resolve_npc_periodic_tribulation(*args, **kwargs),
        _roll_recruit_age_lifespan=lambda *args, **kwargs: engine._roll_recruit_age_lifespan(*args, **kwargs),
        _scale_npc_lifespan=lambda *args, **kwargs: engine._scale_npc_lifespan(*args, **kwargs),
        _select_npc_treasure=lambda *args, **kwargs: engine._select_npc_treasure(*args, **kwargs),
        _stable_secret_art_roll=lambda *args, **kwargs: engine._stable_secret_art_roll(*args, **kwargs),
        _tribulation_base_power_cap=lambda *args, **kwargs: engine._tribulation_base_power_cap(*args, **kwargs),
        _world_realm_cap=lambda *args, **kwargs: engine._world_realm_cap(*args, **kwargs),
        _world_supports=lambda *args, **kwargs: engine._world_supports(*args, **kwargs),
        _get_events_by_id=lambda: engine.events_by_id,
    )


def bind_world_relationships(engine: GameEngine, *, bloodline_content_available: Callable[[], bool]) -> RelationshipDependencies:
    return RelationshipDependencies(
        _actual_player_realm=lambda *args, **kwargs: engine._actual_player_realm(*args, **kwargs),
        _advance_npc_cultivation=lambda *args, **kwargs: engine._advance_npc_cultivation(*args, **kwargs),
        _all_world_npcs=lambda *args, **kwargs: engine._all_world_npcs(*args, **kwargs),
        _filter_personal_revenge_by_protection=lambda *args, **kwargs: engine._filter_personal_revenge_by_protection(*args, **kwargs),
        _find_npc=lambda *args, **kwargs: engine._find_npc(*args, **kwargs),
        _high_affinity_npcs=lambda *args, **kwargs: engine._high_affinity_npcs(*args, **kwargs),
        _instantiate_event=lambda *args, **kwargs: engine._instantiate_event(*args, **kwargs),
        _npc_cultivation_perception=lambda *args, **kwargs: engine._npc_cultivation_perception(*args, **kwargs),
        _npc_faction_id=lambda *args, **kwargs: engine._npc_faction_id(*args, **kwargs),
        _npc_power=lambda *args, **kwargs: engine._npc_power(*args, **kwargs),
        _npc_realm_name=lambda *args, **kwargs: engine._npc_realm_name(*args, **kwargs),
        _npc_root_name=lambda *args, **kwargs: engine._npc_root_name(*args, **kwargs),
        _persist_relationship_npc=lambda *args, **kwargs: engine._persist_relationship_npc(*args, **kwargs),
        _personal_npcs=lambda *args, **kwargs: engine._personal_npcs(*args, **kwargs),
        _random_npc_root=lambda *args, **kwargs: engine._random_npc_root(*args, **kwargs),
        _record_revenge_trigger=lambda *args, **kwargs: engine._record_revenge_trigger(*args, **kwargs),
        _recruit_sect_npc=lambda *args, **kwargs: engine._recruit_sect_npc(*args, **kwargs),
        _relationship_snapshot=lambda *args, **kwargs: engine._relationship_snapshot(*args, **kwargs),
        _resolve_npc_periodic_tribulation=lambda *args, **kwargs: engine._resolve_npc_periodic_tribulation(*args, **kwargs),
        _retaliatory_relationship_ids=lambda *args, **kwargs: engine._retaliatory_relationship_ids(*args, **kwargs),
        _revenge_cooldown_key=lambda *args, **kwargs: engine._revenge_cooldown_key(*args, **kwargs),
        _revenge_ready=lambda *args, **kwargs: engine._revenge_ready(*args, **kwargs),
        _sage_affinity_gain=lambda *args, **kwargs: engine._sage_affinity_gain(*args, **kwargs),
        _scale_npc_lifespan=lambda *args, **kwargs: engine._scale_npc_lifespan(*args, **kwargs),
        _sect_members=lambda *args, **kwargs: engine._sect_members(*args, **kwargs),
        _stable_gender=lambda *args, **kwargs: engine._stable_gender(*args, **kwargs),
        _sync_relationship_records=lambda *args, **kwargs: engine._sync_relationship_records(*args, **kwargs),
        _get_events_by_id=lambda: engine.events_by_id,
        bloodline_content_available=bloodline_content_available,
    )


def bind_world_factions(engine: GameEngine) -> FactionDependencies:
    return FactionDependencies(
        _actual_player_realm=lambda *args, **kwargs: engine._actual_player_realm(*args, **kwargs),
        _add_opportunity=lambda *args, **kwargs: engine._add_opportunity(*args, **kwargs),
        _advance_diplomacy_unit=lambda *args, **kwargs: engine._advance_diplomacy_unit(*args, **kwargs),
        _advance_npc_cultivation=lambda *args, **kwargs: engine._advance_npc_cultivation(*args, **kwargs),
        _advance_wars_unit=lambda *args, **kwargs: engine._advance_wars_unit(*args, **kwargs),
        _all_world_npcs=lambda *args, **kwargs: engine._all_world_npcs(*args, **kwargs),
        _annual_offspring_and_family_update=lambda *args, **kwargs: engine._annual_offspring_and_family_update(*args, **kwargs),
        _annual_relationship_update=lambda *args, **kwargs: engine._annual_relationship_update(*args, **kwargs),
        _cache_encounter_target=lambda *args, **kwargs: engine._cache_encounter_target(*args, **kwargs),
        _check_sect_extinction=lambda *args, **kwargs: engine._check_sect_extinction(*args, **kwargs),
        _compact_sect_roster=lambda *args, **kwargs: engine._compact_sect_roster(*args, **kwargs),
        _dynamic_sect_title=lambda *args, **kwargs: engine._dynamic_sect_title(*args, **kwargs),
        _ensure_race_relations=lambda *args, **kwargs: engine._ensure_race_relations(*args, **kwargs),
        _ensure_sect_relations=lambda *args, **kwargs: engine._ensure_sect_relations(*args, **kwargs),
        _faction_meta=lambda *args, **kwargs: engine._faction_meta(*args, **kwargs),
        _generate_cultivator_target=lambda *args, **kwargs: engine._generate_cultivator_target(*args, **kwargs),
        _governance_threshold=lambda *args, **kwargs: engine._governance_threshold(*args, **kwargs),
        _instantiate_event=lambda *args, **kwargs: engine._instantiate_event(*args, **kwargs),
        _intrigue_enabled=lambda *args, **kwargs: engine._intrigue_enabled(*args, **kwargs),
        _intrigue_has_decision_authority=lambda *args, **kwargs: engine._intrigue_has_decision_authority(*args, **kwargs),
        _intrigue_is_imprisoned=lambda *args, **kwargs: engine._intrigue_is_imprisoned(*args, **kwargs),
        _maybe_npc_found_power=lambda *args, **kwargs: engine._maybe_npc_found_power(*args, **kwargs),
        _maybe_transfer_player_dependency=lambda *args, **kwargs: engine._maybe_transfer_player_dependency(*args, **kwargs),
        _npc_faction_id=lambda *args, **kwargs: engine._npc_faction_id(*args, **kwargs),
        _npc_lethal_chance=lambda *args, **kwargs: engine._npc_lethal_chance(*args, **kwargs),
        _npc_power=lambda *args, **kwargs: engine._npc_power(*args, **kwargs),
        _npc_realm_name=lambda *args, **kwargs: engine._npc_realm_name(*args, **kwargs),
        _player_allegiance_race=lambda *args, **kwargs: engine._player_allegiance_race(*args, **kwargs),
        _power_name=lambda *args, **kwargs: engine._power_name(*args, **kwargs),
        _pressure_weak_npc_powers=lambda *args, **kwargs: engine._pressure_weak_npc_powers(*args, **kwargs),
        _race_power=lambda *args, **kwargs: engine._race_power(*args, **kwargs),
        _random_race_diplomacy_event=lambda *args, **kwargs: engine._random_race_diplomacy_event(*args, **kwargs),
        _random_sect_diplomacy_event=lambda *args, **kwargs: engine._random_sect_diplomacy_event(*args, **kwargs),
        _record_revenge_trigger=lambda *args, **kwargs: engine._record_revenge_trigger(*args, **kwargs),
        _recruit_sect_npc=lambda *args, **kwargs: engine._recruit_sect_npc(*args, **kwargs),
        _resolve_npc_periodic_tribulation=lambda *args, **kwargs: engine._resolve_npc_periodic_tribulation(*args, **kwargs),
        _revenge_ready=lambda *args, **kwargs: engine._revenge_ready(*args, **kwargs),
        _sect_members=lambda *args, **kwargs: engine._sect_members(*args, **kwargs),
        _sect_power=lambda *args, **kwargs: engine._sect_power(*args, **kwargs),
        _set_diplomatic_relation=lambda *args, **kwargs: engine._set_diplomatic_relation(*args, **kwargs),
        _simulate_cultivator_duel=lambda *args, **kwargs: engine._simulate_cultivator_duel(*args, **kwargs),
        _start_war=lambda *args, **kwargs: engine._start_war(*args, **kwargs),
        _world_supports=lambda *args, **kwargs: engine._world_supports(*args, **kwargs),
        _get_events_by_id=lambda: engine.events_by_id,
    )


def bind_hostility(engine: GameEngine) -> HostilityDependencies:
    return HostilityDependencies(
        _actual_player_realm=lambda *args, **kwargs: engine._actual_player_realm(*args, **kwargs),
        _add_enemy_party=lambda *args, **kwargs: engine._add_enemy_party(*args, **kwargs),
        _all_world_npcs=lambda *args, **kwargs: engine._all_world_npcs(*args, **kwargs),
        _available_bounty_authorities=lambda *args, **kwargs: engine._available_bounty_authorities(*args, **kwargs),
        _cache_encounter_target=lambda *args, **kwargs: engine._cache_encounter_target(*args, **kwargs),
        _check_sect_extinction=lambda *args, **kwargs: engine._check_sect_extinction(*args, **kwargs),
        _combat=lambda *args, **kwargs: engine._combat(*args, **kwargs),
        _default_npc_main_technique=lambda *args, **kwargs: engine._default_npc_main_technique(*args, **kwargs),
        _die=lambda *args, **kwargs: engine._die(*args, **kwargs),
        _find_npc=lambda *args, **kwargs: engine._find_npc(*args, **kwargs),
        _generate_cultivator_target=lambda *args, **kwargs: engine._generate_cultivator_target(*args, **kwargs),
        _hostility_entity_members=lambda *args, **kwargs: engine._hostility_entity_members(*args, **kwargs),
        _hostility_entity_state=lambda *args, **kwargs: engine._hostility_entity_state(*args, **kwargs),
        _hostility_key=lambda *args, **kwargs: engine._hostility_key(*args, **kwargs),
        _hostility_name=lambda *args, **kwargs: engine._hostility_name(*args, **kwargs),
        _imprison_or_execute=lambda *args, **kwargs: engine._imprison_or_execute(*args, **kwargs),
        _instantiate_event=lambda *args, **kwargs: engine._instantiate_event(*args, **kwargs),
        _intrigue_record_player_prison=lambda *args, **kwargs: engine._intrigue_record_player_prison(*args, **kwargs),
        _npc_faction_id=lambda *args, **kwargs: engine._npc_faction_id(*args, **kwargs),
        _npc_power=lambda *args, **kwargs: engine._npc_power(*args, **kwargs),
        _npc_realm_name=lambda *args, **kwargs: engine._npc_realm_name(*args, **kwargs),
        _player_allegiance_race=lambda *args, **kwargs: engine._player_allegiance_race(*args, **kwargs),
        _player_battle_power=lambda *args, **kwargs: engine._player_battle_power(*args, **kwargs),
        _player_protected_npc_ids=lambda *args, **kwargs: engine._player_protected_npc_ids(*args, **kwargs),
        _queue_wanted_settlement=lambda *args, **kwargs: engine._queue_wanted_settlement(*args, **kwargs),
        _record_former_jailer_dissolved=lambda *args, **kwargs: engine._record_former_jailer_dissolved(*args, **kwargs),
        _record_revenge_trigger=lambda *args, **kwargs: engine._record_revenge_trigger(*args, **kwargs),
        _retaliatory_relationship_ids=lambda *args, **kwargs: engine._retaliatory_relationship_ids(*args, **kwargs),
        _revenge_ready=lambda *args, **kwargs: engine._revenge_ready(*args, **kwargs),
        _sect_members=lambda *args, **kwargs: engine._sect_members(*args, **kwargs),
        _wanted_target=lambda *args, **kwargs: engine._wanted_target(*args, **kwargs),
        _world_coalition_amnesty_fame=lambda *args, **kwargs: engine._world_coalition_amnesty_fame(*args, **kwargs),
        _world_supports=lambda *args, **kwargs: engine._world_supports(*args, **kwargs),
        _get_events_by_id=lambda: engine.events_by_id,
    )
