/* Short coach marks. Long reference text remains in Settings. */
window.TutorialSteps={
  welcome:{target:'#action-heading',title:'这次，亲手走一遍',text:'跟着箭头操作。教学中的修炼、探宝、拜师和入门都有确定结果，不消耗年月；普通游玩仍按按钮标注的耗时与规则进行。',read:true},
  identity:{target:'.hud-identity, .composition-details',title:'先看看自己',text:'请点击高亮的人物入口，打开人物详情。',click:true},
  roots:{target:'#root-efficiency',context:'details',title:'资质与成长',text:'这里是机缘效率。灵根影响修行积累，功法与天地环境也会影响成长。机缘用来修行，灵石用来交易；气血与法力则是行动的底气。',read:true},
  close_identity:{target:'[data-close-dialog="player-details-dialog"]',context:'details',title:'回到修行主界面',text:'请点“返回主界面”，准备亲自运气。',click:true},
  practice:{target:'#cultivate-action',context:'daily',title:'亲自修炼一次',action:'guide_practice',text:g=>g.practice_gain?'请点击“潜心修炼”。此次试行一周天，固定获得 5 点机缘，不耗岁月、不触发其他事件，也不自动突破。':'请点击“潜心修炼”体验入口。当前角色只观察运气方式，不改变修为或资质。'},
  gain:{target:'#hud-opportunity',title:'看见刚才的变化',text:g=>`${g.last_result} 平时积累充足后，还要关注突破条件、寿元和渡劫准备。`,read:true},
  living:{target:'#tab-living',title:'不只靠闭关成长',text:'请切换到“历练与生计”。探宝、游历和委托各有不同收获。',click:true},
  treasure:{target:'[data-action="treasure"]',context:'living',title:'找到第一份收获',action:'guide_treasure',text:g=>g.beginner?`请点“寻幽探宝”。这次固定找到 3 枚灵石${g.art?`与一份《${g.art.name}》玉简`:''}，不耗岁月。首次所得功法收入已悟功法，重复玉简留在行囊。`:'请点“寻幽探宝”认识入口。高境界角色只演示，不领取入门物资。'},
  bag:{target:'[data-panel-target="inventory"]',title:'亲手打开行囊',text:'请点“行囊”，看看刚才找到的资源。电脑从左侧打开；手机可从“常用”或“百艺”找到它。',click:true},
  resources:{target:'#inventory-card h2',context:'inventory',title:'资源有了去处',text:g=>`${g.last_result} 平时可在坊市买卖、完成商盟委托，或用灵田与百艺建立供给。请留意丹药和材料的用途。`,read:true},
  close_bag:{target:'#inventory-toggle',context:'inventory',title:'收好行囊',text:'请关闭行囊，接下来亲自配置功法。',click:true},
  arts_identity:{target:'.hud-identity, .composition-details',title:'学会之后，还要配置',text:'请再次点人物入口；功法在人物详情里管理。',click:true},
  library:{target:'.technique-library > summary',context:'details',title:'打开已悟功法',text:'请展开“已悟功法”。功法分主修、辅助、战斗、炼体与神识等用途，品阶和修炼层次也各有意义。',click:true},
  equip:{target:'[data-guide-equip]',context:'details',title:'把功法用起来',action:'guide_equip',text:g=>g.art?`请点《${g.art.name}》旁的“主”，将它配置为主修。不同功法侧重不同，适合眼下的自己比只看品阶更重要。`:'当前没有可合法配置的主修功法。本课保留你的道途与所学，可先继续。'},
  art_result:{target:'#technique',context:'details',title:'确认主修已经改变',text:g=>`${g.last_result} 修为、炼体和神识各自成长；炼体与神识需要相应功法，不能只顾一个战力数字。`,read:true},
  close_arts:{target:'[data-close-dialog="player-details-dialog"]',context:'details',title:'走出洞府',text:'请返回主界面，去结识一位授业前辈。',click:true},
  travel_tab:{target:'#tab-living',title:'走向修仙界',text:'请点“历练与生计”。接下来这次游历会遇到预先约定的师缘。',click:true},
  meet:{target:'[data-action="travel"]',context:'living',title:'一次确定的相遇',action:'guide_meet',text:g=>g.mentor_reason||'请点“下山游历”。这次必定遇见结丹后期修士沈照尘，不耗岁月；下一步由你亲自决定是否拜师。'},
  mentor_choice:{target:'#event-choices',title:'在事件里作出选择',text:g=>g.mentor_reason||'请点击事件里的选项。执弟子礼必定拜师成功；谢绝不损声望。事件说明会告诉你处境，选择之前先读清后果。',event:true},
  relationships:{target:'[data-panel-target="relationship"]',title:'师承落在真实关系里',text:'请打开“关系”，查看师徒、道友、道侣与同行。“同道”中也能找到它。',click:true},
  npc:{target:'#relationship-card h2',context:'relationship',title:'同道也有自己的一生',text:'拜师后可在这里向师父请益。NPC 会修炼、远行、结交和陨落；平常请托未必如愿，好感和共同经历也有分量。',read:true},
  close_relationships:{target:'#relationship-toggle',context:'relationship',title:'再找一处山门',text:'请关闭关系窗口，接下来加入宗门。',click:true},
  faction:{target:'[data-panel-target="faction"]',title:'亲自走进宗门',text:'请点击“宗门”。入门不仅能得到同门与福利，也会承担门内事务。电脑从右侧打开；手机可从“经营”找到它。',click:true},
  join:{target:'.tutorial-faction-join',context:'faction',title:'选择你的宗门',text:(g,d)=>d.faction.member?'你已有宗门，本课保留现有归属。请继续查看门内身份。':g.admissions.length?'先在下方选宗门，再点击箭头指向的入门按钮。本次引荐保证接纳，不耗灵石或年月；这是你真实的宗门归属。':'当前没有可接受教学引荐的宗门，本课仅介绍门内事务。',join:true},
  sect:{target:'#faction-role',context:'faction',title:'你已有门内身份',text:(g,d)=>d.faction.member?`你现在属于${d.faction.name}，身份显示在高亮处。门人名单、年度福利与宗门贡献都在这个窗口；宗门也会卷入争斗。`:'日后符合招募条件时，可在游历中遇到入门机会。已有宗门后，这里会显示身份、同门与福利。',read:true},
  close_faction:{target:'#faction-toggle',context:'faction',title:'记住这处山门',text:'请关闭宗门窗口，再看看你所在的天地。',click:true},
  map:{target:'[data-panel-target="map"]',title:'远行前先看路',text:'请打开“地图”。电脑从右侧打开；手机可从“常用”或“诸界”找到它。',click:true},
  roads:{target:'#map-current',context:'map',title:'路程也是修行成本',text:'移动会消耗路线标注的时间，传送需要许可或承担偷渡风险。境界更高以后，一次日常行动也可能跨过漫长岁月。此次只看地图，不移动。',read:true},
  close_map:{target:'#map-toggle',context:'map',title:'先定一个小目标',text:'请关闭地图。你可以先准备突破，也可以经营师门、百艺或同道关系；长生与游历诸界是更远的目标。',click:true},
  settings:{target:'[data-panel-target="settings"]',title:'以后忘记了怎么办',text:'请打开“设置”。这里可以调主题、战斗预案，也能暂停或续接教程。',click:true},
  handbook:{target:'#tutorial-handbook summary',context:'settings',title:'说明留在需要的时候查',text:'请展开第一篇修行指南。完整说明放在这里，今后可按需查阅。',click:true},
  finish:{target:'#setting-tutorial-open',context:'settings',title:'现在，自己走下一步',text:'你已亲手用过修炼、探宝、功法、关系、宗门和地图。以一次突破或一次师门请益为下个目标吧；导出存档码可以把这一世带到另一台设备。',read:true},
};
