const $=s=>document.querySelector(s);let config,game,busy=false;
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const value=await response.json();if(!response.ok)throw Error(value.error||'命令失败');return value}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
async function boot(){[config,{games:window.saves}]=await Promise.all([api('/api/v2/config'),api('/api/v2/games')]);fill('#roots',config.roots);fill('#paths',config.paths);renderSaves()}
function fill(selector,rows){$(selector).innerHTML=Object.entries(rows).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}
function renderSaves(){$('#saves').innerHTML=(window.saves||[]).map(row=>`<button data-id="${row.game_id||row.id}">续接 · ${row.player_name||row.name}</button>`).join('');$('#saves').querySelectorAll('button').forEach(x=>x.onclick=()=>load(x.dataset.id))}
async function load(id){game=await api(`/api/v2/games/${id}`);render()}
async function command(operation,payload={}){if(busy)return;busy=true;try{const result=await api(`/api/v2/games/${game.id}/${operation}`,{method:'POST',body:JSON.stringify(payload)});game=result.game||result;render()}catch(e){toast(e.message)}finally{busy=false}}
function render(){ $('#start').classList.add('hidden');$('#game').classList.remove('hidden');$('#name').textContent=game.player.name;const c=game.player.cultivation;$('#realm').textContent=`${c.realm_name} · ${c.layer}层 · 纪年 ${game.clock.year}`;$('#stats').innerHTML=[['年龄',game.player.age],['寿元',game.player.lifespan??'不朽'],['机缘',`${Math.round(c.opportunity)}/${c.opportunity_required}`],['心魔',Math.round(c.heart_demon)],['世界',game.world.world_name]].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');$('#actions').innerHTML=Object.entries(config.actions).map(([id,name])=>`<button data-action="${id}">${name}</button>`).join('');$('#actions').querySelectorAll('button').forEach(x=>x.onclick=()=>command('advance',{action:x.dataset.action,units:1}));const event=game.pending_event;$('#event').classList.toggle('hidden',!event);if(event){$('#event-title').textContent=event.title;$('#event-body').textContent=event.body;$('#choices').innerHTML=event.choices.map(x=>`<button data-id="${x.id}" ${x.enabled?'':'disabled'}>${x.text}</button>`).join('');$('#choices').querySelectorAll('button').forEach(x=>x.onclick=()=>command('choice',{choice_id:x.dataset.id}))}showPanel('intrigue_system')}
function showPanel(key){$('#panel').textContent=JSON.stringify(game[key],null,2)}
document.querySelectorAll('[data-panel]').forEach(x=>x.onclick=()=>showPanel(x.dataset.panel));$('#new').onclick=()=>{$('#game').classList.add('hidden');$('#start').classList.remove('hidden')};$('#create').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));if(!p.seed)delete p.seed;else p.seed=Number(p.seed);try{game=await api('/api/v2/games',{method:'POST',body:JSON.stringify(p)});render()}catch(error){toast(error.message)}};boot().catch(e=>toast(e.message));
